# Generated by Django 5.0.3 on 2024-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_idRol', models.IntegerField()),
                ('usuarios_idUsuarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol_opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion', models.CharField(max_length=100)),
                ('ide_opcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol_RolOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_idRol', models.IntegerField()),
                ('rol_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_idRol', models.IntegerField()),
                ('Usuarios_idUsuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('usuario_idUsuario', models.IntegerField()),
            ],
        ),
    ]
